### ISSUE TITLE
Internationalize landing page sections

### ISSUE THREAD

**Issue by micorix** [po8klasie/po8klasie#196]
Provide landing page translations based on #195 (wait for it to be merged)

Use sections separate as different object within same json file.

Json files can be translated using Google Translator or left with original polish content. For now setting up i18n mechanisms are more important than translations quality which we will work later on.

medium-high priority, but backend should be a priorityfor you as in case of sth I can work on this task as well

Please provide ETA

In case of any questions hmu

**Comment by micorix** [comment]
Helpful docs:
https://github.com/isaachinman/next-i18next
https://nextjs.org/docs/advanced-features/i18n-routing
https://react.i18next.com/latest/usetranslation-hook

**Comment by Anakin100100** [comment]
@micorix I can't push commits to new branches because I'm not in the frontend team.

**Comment by micorix** [comment]
I'll try to adjust access perms (write access for org memebers) but you can still make a PR from fork

**Comment by micorix** [comment]
@Anakin100100  What's the ETA?

**Comment by Anakin100100** [comment]
I should be able to finish it today

**Comment by micorix** [comment]
#198

**Comment by Anakin100100** [comment]
@micorix can we merge #198 and close this issue?

**Comment by micorix** [comment]
Merged
