### ISSUE TITLE
Favourites breadcrumbs

### ISSUE THREAD

**Issue by karmek-k** [po8klasie/po8klasie#64]
#52

**Comment by micorix** [comment]
@karmek-k I'm assinging you to this issue

**Comment by karmek-k** [comment]
@micorix
Ok, but is the CORS issue going to be fixed any time soon? Or should I set my own backend instance for now?

**Comment by micorix** [comment]
This is the first time we encounter that bug. I'll check a few things, ask @mlazowik and come back to you.

As a temporary workaround you can use Moesif Origin & CORS Changer browser extension.

**Comment by karmek-k** [comment]
I considered your suggestion:

> How about adding some property to location state and handling it "internally" 🙂 ?

So I created an enum that contains possible sources of navigating to the school page:

```typescript
export enum Source {
  SchoolSearchPage,
  FavouriteSchoolsPage,
}
```

And a map that maps the above enum's values to `Breadcrumbs` component props:
```typescript
export const sourceMap = new Map<Source, string[]>([
  [Source.SchoolSearchPage, ['Wyszukiwarka szkół', '/schools']],
  [Source.FavouriteSchoolsPage, ['Ulubione szkoły']],
]);
```

I added `source` as a nullable prop to `SchoolPage`:
```typescript
const SchoolPage = (props: RouteComponentProps<{ schoolID: string, source?: Source }>) => {
  // ...
};
```

And finally, pass it to sourceMap in Breadcrumbs component:
```typescript
<Breadcrumbs
  steps={[
    [sourceMap.get(props.source ?? Source.SchoolSearchPage)],
    [school ? school.school_name : 'Szkoła'],
  ]}
/>
```

A `Link` to SchoolPage can pass a `state` prop with `source`, but I haven't implemented that yet.

What do you think @micorix ? I know that the implementation is far from perfect, but I can improve it with your suggestions.

**Comment by micorix** [comment]
Hi. It seems nice :slightly_smiling_face:. Please open a PR with full implementation so we can play a bit with it and tell you more.

One thing I would change now is `utils/source.ts` filename. I think `source` is too generic and doesn't clearly describe what's in there.

**Comment by micorix** [comment]
@karmek-k any progress :) ?

**Comment by micorix** [comment]
Outdated, closing
